server:
  port: 5678
spring:
  redis:
    database: 0
    host: redis的ip
    port: 6379
    password: 密码
    timeout: 0
    pool:
      max-active: 2000
      max-idle: 20
      # 最小空闲连接数（默认为0，该值只有为正数才有用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 600MB
GaoDe:
  key: "高德地图key，获取天气数据"
TianXing:
  key: "天行数据key"
WeChat:
  appid: "微信appid"
  secret: "微信secret"
